# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - current
        - lts/hydrogen
        - lts/gallium
        - lts/fermium
        - lts/erbium
        axios-version:
        - latest
        - ~1.1.0
        - ~1.0.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm install axios@${{ matrix.axios-version }}
        test '${{ matrix.node-version }}' = 'current' && npm run lint
        test '${{ matrix.node-version }}' = 'current' && npm run typing
        npx nyc --reporter=text --reporter=lcov npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
